### PR TITLE
[#112] Added Xorg, SDL2 and GL support

### PR DESCRIPTION
**Pull request by nikp123**

### CODE REVIEW

**Comment by nikp123** [comment]
It also contains some bugfixes.

**Comment by karlstav** [comment]
I will have to do some testing before I can merge this. I also have to do some considerations on whether or not I can maintain all this extra functionality or if it diverts to much from the original project. 

Right now time is limited, I will get back to this.

**Comment by nikp123** [comment]
@karlstav no problem, I was thinking if you wanted these features that I would merge them with your repository. But I thought to keep my fork seperate, because I would like to experiment with a lot of functionality (which breaks legacy configurations). If you do want to merge stuff, please list them below so I could sort it out.

**Comment by nikp123** [comment]
I think that maintaining graphical modes for cava is going to be hard (as I've spent hours merging incompatible code), so I'm thinking that it's a better idea to keep this as a fork (probably should rename it to gava just to avoid conflicts codewise and configwise). Meanwhile you can still merge the non-graphics code I have, such as portaudio.

**Comment by karlstav** [comment]
@nikp123 agreed, I have tried to look trough your code from time to time, but I haven't been able to grasp it completely. So it is probably best you maintain it yourself.

Also there is already an openGL implementation called [glava](https://github.com/wacossusca34/glava), so maybe gava is not the best name. What about xava?

**Comment by nikp123** [comment]
@karlstav While I like the name, it implies that it's for the X windowing system. Then again the code is really meant for Linux so it's appropriate. I mean I can take it, but I'm just trying to avoid confusion.

**Pull request closed without merging**
