### PR TITLE
Remove cava_LDFLAGS

### PR DESCRIPTION
**Pull request by jubalh**
Not needed.

### CODE REVIEW

**Comment by karlstav** [comment]
are you sure? I must have added them there for a reason, or maybe I just copied them from some example file. What would these flags normally be for?

**Comment by jubalh** [comment]
/usr/local/lib should automatically be available (/etc/ld.so.conf should check for /usr/local/lib64 and /usr/local/lib, /usr/lib and /usr/lib64 are checked already).

there is no reason to use [rpath](https://en.wikipedia.org/wiki/Rpath) is not needed either as those directories are already checked so dont need a preference.

**Comment by karlstav** [comment]
seems reasonable

**Comment by karlstav** [comment]
@jubalh did you consider #84 when you did this?

**Comment by jubalh** [comment]
I dont see a problem.

**Comment by anned20** [comment]
It broke it...

**Comment by karlstav** [comment]
@anned20 have you looked in to #84?  Is it the same problem?

**Comment by anned20** [comment]
Yeah it is. I tried to do that and it worked instantly.

**Comment by jubalh** [comment]
#84 is a hack, not a good solution.

@anned20 which distro?

**Comment by anned20** [comment]
Linux Mint 18.1 Sarah

**Comment by karlstav** [comment]
I am also on mint 18.1, I also get this message during `make install`:

```Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
```

But it works. 

What do you say @jubalh? Restore the LDFLAGS? I agree that it doesn't seem necessary, but  it does solve the problem. I personally do not know enough abut these things to understand what the problem is or what causes it or how to solve it properly. :frowning_face:

**Comment by ibrokemypie** [comment]
How do you change the value/ignore that flag while configuring? No longer builds on arch linux since they removed /usr/local, though builds fine when changed to just /usr

**Comment by jubalh** [comment]
> No longer builds on arch linux since they removed /usr/local, though builds fine when changed to just /usr

@ibrokemypie Arch Linux removed `/usr/local` ?

> How do you change the value/ignore that flag while configuring?

```
export LDFLAGS=-L/usr/local/whatever
./configure # run configure make or whatever
```

Alternatively you can just define it before the command.

**Pull request merged**
