### PR TITLE
With ALSA input, check if the snd_aloop module is loaded

### PR DESCRIPTION
**Pull request by hartwork**
Hi! Here's a patch for issue #55. Please consider application.

### CODE REVIEW

**Comment by karlstav** [comment]
I'm not sure, but people might try to use cava with another type of input like a microphone. (I do it sometime does to show it off....) .

However I think this check could be very useful in the "error opening stream: " error in alsa.c. There it could check if the user hasn't loaded the loopback or is just trying to open the wrong device.

**Comment by hartwork** [comment]
The patch as of now only does that check for ALSA input mode.
Are you referring (a) to non-ALSA input or (b) to ALSA input with something other than a loop device?
Case (a) is covered already.
For case (b) we could turn the error into a warning or add a command line option to skip the check. I like former better as of now.

Best, Sebastian

**Comment by karlstav** [comment]
I was referring to b, other alsa input than loop device.

If we change cava from using 'hw:1,1' as default to 'hw:Loopback,1', we could skip your check whenever the user specifies another device.

**Comment by hartwork** [comment]
I have implemented and pushed those ideas now.

These are the places where I wasn't sure if hw:0/1 should have been touched, too:
```
# grep -R 'hw:[0-9]' .
./example_files/etc/asound.conf:            a { channels 2 pcm "hw:0,0" }  # the real device
./example_files/etc/asound.conf:            b { channels 2 pcm "hw:1,0" }  # the loopback driver
./example_files/config:; source = hw:1,1 # ALSA device or FIFO path.
```

**Comment by hartwork** [comment]
PS: I wonder if `Loopback` is case sensitive or not.

**Comment by karlstav** [comment]
the config file and example asound.conf can be changed to, I'll take care of it. 

Yes it is case sensitive, capital L, so everything looks good.

**Comment by hartwork** [comment]
Excellent!

**Pull request merged**
