### PR TITLE
Refactor input method magic numbers into enum

### PR DESCRIPTION
**Pull request by Xyene**
(This PR is based off of #318, I will rebase it if/when that one is approved.)

### CODE REVIEW

**Comment by karlstav** [comment]
did I pull the wrong request now?

**Comment by Xyene** [comment]
Nope, everything's good, I've rebased this change and https://github.com/karlstav/cava/pull/321.

**Comment by karlstav** [comment]
hmm I get no output after this, bars act like if silence.

**Comment by Xyene** [comment]
@karlstav what input/output methods do you have configured?

**Comment by karlstav** [comment]
none, seems like pulseaudio is no longer defualt.

**Comment by karlstav** [comment]
is `fifo`default now? I think it would be better if pulseaudio is default. If you then have pulseaudio installed in your system it would be a simple install and run to capture audio straight from your system (since the pulseaudio input module is able to do that). Also to have portaudio to default before fifo would be convenient for macos users

**Comment by Xyene** [comment]
Agreed, `fifo` should be picked last. I thought I had maintained the correct order, but looks like I mucked something up. I'll submit a follow-up to fix it.

**Pull request merged**
