### PR TITLE
Compile Cava as multiple object files

### LINKED ISSUE #317: Compile with multiple object files
Currently, Cava has multiple source files, but they are all `#include`d into `cava.c`, which is not a common or recommended practice. We should compile each source file to a separate object file.

### PR DESCRIPTION
**Pull request by quantum5**
Fixes #317.

### CODE REVIEW

**Comment by karlstav** [comment]
feel free to rebase/resolve and thanks again for all the contributions @quantum5 and @Xyene! This is stuff that I would have never had time to do on my own.

**Comment by quantum5** [comment]
@karlstav this is ready now.

**Comment by Xyene** [comment]
@karlstav no problem, happy to help 😄 

For some context: both myself and @quantum5 [have a weird use-case for cava](https://quantum2.xyz/2019/12/16/desktop-audio-visualizer-i3-cava-wsl/) (hence the 24-bit FIFO input, etc.)... on one hand, it looks kinda cool:

image

...on the other, it's only practical (or... not impractical?) if cava + urxvt use as little CPU as possible 😉. In our case at least, the ncurses change + making FFTW aligned for SIMD dropped usage from 20~30% to 0-4%.

**Comment by karlstav** [comment]
look nice, for me CPU usage for cava with a tiny tiny urxvt window is around 5% while full screen terminal is around 10%. I think a full screen window had much higher cpu usage before your much appreciated contributions!

**Pull request merged**
