### PR TITLE
all: remove include *.c from cava.c

### PR DESCRIPTION
**Pull request by chelovechishko**
add common.h and some stuff to make it compiled

### CODE REVIEW

**Comment by karlstav** [comment]
Wow a lot of changes here. I really appreciate you're contribution. Could you give a short explanation on the different things you are doing here? I am not an expert on the `make` stuff so i really just copy pasted and guessed when i first mad this.

Also I got error:

```
In file included from cava.c:21:0:
output/terminal_ncurses.h:1:20: fatal error: common.h: No such file or directory
compilation terminated.
```

But maybe you're not done with it yet?

**Comment by chelovechishko** [comment]
Oops, for somewhat reason there is no common.h. I'll rebase it.

I removed some unneeded *.h, replaced some hardcoded values to defines, make compilation of some files on demand (previously all files were included to cava.c and only it was compiled, now files are being compiled apart).

**Comment by vinodadhikary** [comment]
That indeed is a heavy refactoring! It appears about time to include some tests and changelogs. I can contribute; please let me know how I can be of help.

**Comment by karlstav** [comment]
@vinodadhikary tests would be great! Do you mean something like Travis CI? I looked into it briefly some time back, but due to my lack of knowledge in this field I gave up :worried: There is already an issue about automated unit testing #21 raised over two years back, is that the same thing? If so, maybe we can continue the discussion there.

I don't even know where to begin with this, so any input is much appreciated.

**Comment by vinodadhikary** [comment]
@karlstav, yes my comment is more related to #21. Sure, we can use Travis CI but only after we have good code/test coverage. For that we need some tests. I will continue the discussion there. I see that there are few other willing to contribute to testing already!

**Comment by karlstav** [comment]
@chelovechishko it fails to build on my pi :frowning_face: 
```
input/cava-alsa.o: In function `initialize_audio_parameters':
/home/pi/chcava/input/alsa.c:20: undefined reference to `alloca'
collect2: error: ld returned 1 exit status
Makefile:523: recipe for target 'cava' failed
make[1]: *** [cava] Error 1
make[1]: Leaving directory '/home/pi/chcava'
Makefile:716: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

running: `Raspbian GNU/Linux 8.0 (jessie)`

**Comment by chelovechishko** [comment]
Included alloca.h to alsa.c. Rebased once more.

**Comment by karlstav** [comment]
great!

can you take a look at this warnings as well:
```
cava.c:922:33: warning: implicit declaration of function ‘getch’ [-Wimplicit-function-declaration]
    if (om == 1 || om == 2) ch = getch();
```

```
output/terminal_ncurses.c: In function ‘draw_terminal_ncurses’:
output/terminal_ncurses.c:176:7: warning: implicit declaration of function ‘mvaddwstr’ [-Wimplicit-function-declaration]
       mvaddwstr((height - n), CURRENT_COLUMN,
       ^
```

```
output/terminal_bcircle.c: In function ‘draw_terminal_bcircle’:
output/terminal_bcircle.c:72:5: warning: implicit declaration of function ‘mvaddwstr’ [-Wimplicit-function-declaration]
     mvaddwstr(y,x,bars[7]);
     ^
```

the last two is only on my pi (ncurser version 5.9.20140913), but everything works fine (including ncurses)

**Comment by chelovechishko** [comment]
Sigh, i accidentally closed it again... Now it must compile without this warnings.

**Pull request merged**
