### PR TITLE
Small code readability fixes.

### PR DESCRIPTION
**Pull request by CelestialWalrus**

### CODE REVIEW

**Comment by livibetter** [comment]
Confession time, an hour ago, I created a branch named `real-devs-dont-spell` (aka. `spell-not-a-real-word`), half way of fixing typos, I bailed out, enough funny moment for me in a short time.

@CelestialWalrus you should add another commit, 7107d7b doesn't seem to take care of typos. Especially, those in help text. I also think the help text has too many newlines, those blank lines between options.

**Comment by CelestialWalrus** [comment]
@karlstav don't merge it yet, I'll improve it as @livibetter suggests.

**Comment by anko** [comment]
@CelestialWalrus Same branch can be merged many times to bring in more commits, don't worry. :)

**Comment by CelestialWalrus** [comment]
@anko @livibetter I'm done. Any other suggestions?

**Comment by anko** [comment]
Did you mean 1a32055 to be on another branch? [L314's `getopt` call](https://github.com/CelestialWalrus/cava/commit/1a320552752147f69b89a03be6a84595dce33f4c#diff-10fcdb86aea9ceffa1373be8d7f2b15dR314) has no "o": `-o` doesn't parse.

Lots of tabs-spaces mixing still, but this is definitely an improvement.

**Comment by CelestialWalrus** [comment]
@anko: no, it's meant to be there, but disabled. (i.e. no one can use it)

**Comment by karlstav** [comment]
oh no, all my terrible typos are being cleaned up. More will probably turn up :) great work!

**Pull request merged**
