### PR TITLE
Synchronized Sync (Mode 2026)

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Deprecates the Alacritty synchronization option for Mode 2026 (https://gist.github.com/christianparpart/d8a62cc1ab659194337d73e399004036)

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
@karlstav Tested in ghostty, alacritty, kitty, and gnome console. This is a naive implementation but it does seem to work.

**Comment by karlstav** [comment]
hi @ThatOneCalculator,

sorry for the late feedback. There is one thing I don't understand. Why is there both a begin and end update before and after the draw function? Shouldn't there be BSU (2026h) before (line 1101) and ESU (2026l) after (line 1152)?

**Comment by ThatOneCalculator** [comment]
To be honest, this was a very naive implementation -- I did it to the point where it worked, but I think that I probably made a mistake or two along the way. I am not a C programmer nor a terminal UI programmer, but this fixed works for me, although I doubt it's the right way to do things. Something about having the update go through even though it immediately gets ended makes ghostty not tear. I think it could probably work as you described having the BSU before and the ESU after. Feel free to change my implementation!

**Comment by karlstav** [comment]
If it works, it works. A couple of things though: if the old alacritty sync thing has not been deprecated by alacritty i think we should keep it along side this one. Also I think this sync method also must be a config option and that it must be default off. Never know if it can cause issues.

**Comment by ThatOneCalculator** [comment]
Afaik alacritty now uses the new standard. Tested this on kitty/ghostty/alactitty/foot and all worked

**Comment by karlstav** [comment]
noted, https://github.com/alacritty/alacritty/pull/7365

just re apply the config option (I still believe it should be optional) and squash the commits and then I can merge

**Comment by ThatOneCalculator** [comment]
Should hopefully be able to do soon :D

**Comment by ThatOneCalculator** [comment]
Oh shit I kinda forgot about this

**Comment by ThatOneCalculator** [comment]
@karlstav there we go! Sorry about the very long delay

**Comment by ThatOneCalculator** [comment]
Tested properly now. Works completely as expected!

**Comment by karlstav** [comment]
no problem, hmm looks like I can squash the commits when i merge, i did not know that. seemed excessive with 10 commits for the 5 lines of code change.

**Pull request merged**
