### PR TITLE
raw: refactoring

### PR DESCRIPTION
**Pull request by chelovechishko**
Didn't check it.

### CODE REVIEW

**Comment by karlstav** [comment]
ascii still works, but I'm not getting any output from binary :frowning_face:

**Comment by karlstav** [comment]
OK, now I got something. I don't have an application to test if it is correct. But then again I never had. Merge?

**Comment by chelovechishko** [comment]
Sorry @worron Could you check binary output, if you use it?

**Comment by worron** [comment]
Just tried 16bit and it works all ok. I can check 8bit if it necessary, but tomorrow only, it's need a bit time to edit my scripts for 8bit output.

**Comment by chelovechishko** [comment]
Not necessary, the code for both parts is the same. Thank you @worron

**Comment by karlstav** [comment]
I'll merge it then. Thanks again @chelovechishko for the refactoring.

**Pull request merged**
