### PR TITLE
Add a Code Hunt vote badge to README.md

### PR DESCRIPTION
**Pull request by CodeHuntIO**
@karlstav FYI, your repo has been featured today on @CodeHuntIO   

http://codehunt.io/sub/c-a-v-a/

**TL;DR** Code Hunt helps programmers discover awesome code — like yours!   

This pull-request adds a "vote" badge to your README.md:   

[CodeHunt.io](http://codehunt.io/sub/c-a-v-a/?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)   

Fingers crossed that we can drive more attention to your brilliant work.   

Happy coding!
Chris ^_^   

p.s. I hope you found this PR helpful, if not please [let me know](mailto:chris@codehunt.io).   

p.p.s I've also tweeted about you here https://twitter.com/hunt_c_lang/status/626725698972073984

### CODE REVIEW

**Comment by CelestialWalrus** [comment]
@karlstav I'd ignore/close that pull request. Seems spammy.

**Comment by CodeHuntIO** [comment]
@CelestialWalrus a bit spammy indeed ;-). But not a machine... I'm just 1 guy in Australia (@chrisjacob) trying to bootstrap a community around open source. I'm a hopeless marketer - but figured these PRs were worth a shot for repo owners interested in the idea. No hard feelings if you ignore/close. & thx for your contributions to cava!
- Chris

**Comment by anko** [comment]
Meh. Good code is more important than popularity contests.

We also have Github stars already. How is this better?

**Comment by CodeHuntIO** [comment]
@anko agreed, good code speaks for it self and trumps popularity. I'm trying to build a place where lesser known developers have a chance of getting their code seen by a wider audience. Most devs I know would rather spend time coding than blogging/building an audience. So a lot of great code goes unseen. I'm just try to help with that discovery process of hidden gems. Plus even the really popular project can sometimes slip through the cracks of people's radars.  

I was inspired by the "awesome-*" lists https://github.com/sindresorhus/awesome ... I've found a lot of great repos looking over these lists. And wanted to have a place where you can get this feeling every day. Also heavily influence by http://producthunt.com

GitHub Stars work well, but I also think they can favour "celebrities" and "companies" in the developer community ... nothing wrong with that, really. It just make things harder for other individuals to be seen. The voting on Code Hunt is really just a way to surface "what's awesome" within the Code Hunt community... And since this community only launched today it's going to be interesting to see how this pans out ;-)

Appreciate your feed back :-)

**Comment by karlstav** [comment]
@CodeHuntIO Hi Chris,

codehunt seems like a great initiative and I'm honored that you have featured my work on it. But I'm gonna have to pass on the vote bar thing. We already have stars and I want to keep it clean. 

Again, thanks for the feature and best of luck to your project.

* Karl

**Comment by CodeHuntIO** [comment]
@karlstav totally understand, thanks for taking the time to get back to me and for the kind words ^_^

**Pull request closed without merging**
