### PR TITLE
Simple multicolor display

### PR DESCRIPTION
**Pull request by nrhine1**
I made some modifications to make the bars display in multicolor. Right now, it's just based on hardcoded thresholds and alternative colors (green, yellow, red), but it illustrates the concept of the dynamic color switching. Could make it a new branch to isolate development

eq_vis

### CODE REVIEW

**Comment by karlstav** [comment]
Cool feature! This reminds me of early development stages where I actually had multicolor. I discarded it because there was no way to get a smooth gradient and I thought it looked a bit "static". So personally I like it better solid, but if you make multicolor optional and also with configurable colors in the config file, I'll merge it. 

If you want to, I can create a separate branch for it. Maybe someone else wants to do the work of making it optinal, maybe I can do it myself whenever I find time.

**Comment by karlstav** [comment]
@nrhine1 this is still interesting, but I think we should make a separate branch and make it more customizable, before merging it into the master branch. 

Do you know an easy way of automatically merging this into a separate branch?

**Comment by anko** [comment]
@karlstav 

> Do you know an easy way of automatically merging this into a separate branch?

Add @nrhine1's remote, and fetch its contents to the local repository.

```
git remote add nrhine1 "https://github.com/nrhine1/cava.git"
git fetch nrhine1
```

Move to the appropriate tracking branch.

```
git checkout nrhine1/multicolor
```

Create a new local branch at that point.

```
git branch multicolor
```

Push the new local branch to your github remote (assuming your `origin` is github).

```
git push --set-upstream origin multicolor
```

**Comment by karlstav** [comment]
thanks @anko, it is now a separate branch. Should I close this pr?

**Comment by nrhine1** [comment]
Yeah sure

**Pull request closed without merging**
